- name: Create {{ user }} group
  group:
    name: "{{ user }}"

- name: Create {{ user }} user
  user:
    name: "{{ user }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: /bin/bash
    createhome: yes
    group: "{{ user }}"

- name: Add {{ user }} to sudo group
  user:
    name: "{{ user }}"
    groups: sudo
    append: yes

- name: Configuring sudo access without a password for the {{ user }} user
  lineinfile:
    dest: "/etc/sudoers"
    line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"

- name: Create SSH directory if not exists
  file:
    path: /home/{{ user }}/.ssh
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

#- name: Copy authorized keys for the {{ user }} user from local {{ ssh_user }} user
#  copy:
#    src: ~/.ssh/authorized_keys
#    dest: /home/{{ user }}/.ssh/authorized_keys
#    owner: "{{ user }}"
#    group: "{{ user }}"
#    mode: 0600

- name: Copy public keys to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: '{{ item }}'
  with_file: "{{ authorized_keys }}"