- name: Check if {{ package_name }} is installed
  become: yes
  command: git --version
  ignore_errors: yes
  register: git_check
  changed_when: false

- name: Uninstall {{ package_name }} package
  become: yes
  command: apt remove -y git
  when: git_check.stdout is defined

- name: Delete {{ package_name }} configuration settings
  become: yes
  command: apt purge -y git
  when: git_check.stdout is defined

- name: Show {{ package_name }} version
  command: git --version
  register: status_output
  when: git_check.stdout is defined

- name: Print version output
  ansible.builtin.debug:
    var: status_output.stdout_lines
  when: git_check.stdout is defined