- hosts: all
  vars:
    ssh_user: developer
    package_name: net-tools
  remote_user: "{{ ssh_user }}"

  tasks:
    - name: Include {{ package_name }} role for {{ ssh_user }} user
      include_role:
        name: common
        tasks_from: net_tools_install.yaml