---
- name: Первоначальная настройка сервера
  hosts: all
  become: true

  vars_files:
    - /home/ansible-agent/ansible/group_vars/vault.yml

  tasks:
    - name: Подкладывание всех публичных ключей для пользователя root
      ansible.builtin.copy:
        src: "~/ssh-user-key/*"
        dest: "/root/.ssh/"
        mode: '0600'
      become_user: root

    - name: Настройка sudo доступа без пароля для пользователя root
      lineinfile:
        dest: "/etc/sudoers"
        line: "root ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"

    - name: Создание пользователя ansible с паролем
      ansible.builtin.user:
        name: ansible
        password: "{{ ansible_password }}"
        shell: /bin/bash
        createhome: yes
        home: /home/ansible

    - name: Настройка sudo доступа без пароля для пользователя ansible
      lineinfile:
        dest: "/etc/sudoers"
        line: "ansible ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"

    - name: Подкладывание всех публичных ключей для пользователя ansible
      ansible.builtin.copy:
        src: "~/ssh-user-key/*"
        dest: "/home/ansible/.ssh/"
        mode: '0600'
        owner: ansible
        group: ansible

    - name: Изменение пароля пользователя root
      ansible.builtin.user:
        name: root
        password: "{{ root_password }}"


