---
- name: Firts initialization
  hosts: all
  become: true
  vars:
      user: developer
      pwd: developer_user_password

  tasks:
  - name: Include vault
    ansible.builtin.include_vars:
      file: ~/ansible/group_vars/vault.yml
  - name: Add the user {{ user }}
    ansible.builtin.user:
      name: "{{ user }}"
      password: "{{ pwd }}"
      shell: /bin/bash
      createhome: yes
      home: /home/ "{{ user }}"
      group: sudo
  - name: Create a 2048-bit SSH keys for user {{ user }} in ~/.ssh/id_rsa
    ansible.builtin.user:
      name: "{{ user }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa