---
- name: Create user on remote server
  hosts: all
  become: yes

  vars:
      user: admin
      source_user: root

  remote_user: "{{ source_user }}"

  tasks:
    - name: Create {{ user }} group
      group:
        name: "{{ user }}"

    - name: Create {{ user }} user
      user:
        name: "{{ user }}"
        password: "{{ 'Ansible1234' | password_hash('sha512') }}"
        shell: /bin/bash
        createhome: yes
        group: "{{ user }}"

    - name: Add ansibleuser to sudo group
      user:
        name: "{{ user }}"
        groups: sudo
        append: yes

    - name: Configuring sudo access without a password for the {{ user }} user
      lineinfile:
        dest: "/etc/sudoers"
        line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"

    - name: Create SSH directory if not exists
      file:
        path: /home/{{ user }}/.ssh
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0700

    - name: Copy authorized keys {{ source_user }} >> {{ user }}
      copy:
        src: ~/.ssh/authorized_keys
        dest: /home/{{ user }}/.ssh/authorized_keys
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600