---
#Run this playbook with flag --ask-pass <root_pass>
- name: Copy SSH public ket to remote servers
  hosts: all
  remote_user: root

  vars:
      user: root

  tasks:
    - name: Create SSH directory if not exists
      file:
        path: /{{ user }}/.ssh
        state: directory
        mode: '0700'

    - name: Copy public keys to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ user }}"
        state: present
        key: '{{ item }}'
      with_file:
        - ~/.ssh/id_rsa.pub
        - ~/.ssh/main_rsa.pub

    - name: Configuring sudo access without a password for the {{ user }} user
      lineinfile:
        dest: "/etc/sudoers"
        line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"

#####   ALTERNATIVE OPTION   #####

#    - name: Copy public keys to authorized_keys
#      authorized_key:
#        user: "{{ user }}"
#        key: "{{ lookup('file', '/home/ansible-agent/.ssh/id_rsa.pub') }}"
#
#    - name: Copy main public key to authorized_keys
#      authorized_key:
#        user: "{{ user }}"
#        key: "{{ lookup('file', '/home/ansible-agent/.ssh/main_rsa.pub') }}"