- hosts: all
  become: yes
  vars:
    ssh_user: root
    config_user: admin

  remote_user: "{{ ssh_user }}"

  tasks:
    # Decrypt Vault file and load variables
    - name: Load user credentials configuration from Vault
      include_vars:
        file: ~/ansible/vault/users/cfg_users.yaml

    - name: Add ssh-key and disable password auth for {{ ssh_user }}
      include_role:
        name: ubuntu
      vars:
        user: "{{ ssh_user }}"

    - name: Include user-setup role for {{ user }} user
      include_role:
        name: ubuntu
        tasks_from: create_config_user.yaml
      vars:
        user_password: "{{ users[user].password }}"